[rospy.client][INFO] 2020-02-27 09:00:56,517: init_node, name[/sr_determine_rois_17927_1582774256480], pid[17927]
[xmlrpc][INFO] 2020-02-27 09:00:56,518: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-02-27 09:00:56,519: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:33509/]
[rospy.impl.masterslave][INFO] 2020-02-27 09:00:56,519: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:33509/
[xmlrpc][INFO] 2020-02-27 09:00:56,521: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-02-27 09:00:56,520: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:33509/]
[rospy.registration][INFO] 2020-02-27 09:00:56,521: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2020-02-27 09:00:56,521: registering subscriber topic [/usb_cam/image_rect] type [sensor_msgs/Image] with master
[rospy.internal][INFO] 2020-02-27 09:00:56,527: topic[/usb_cam/image_rect] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:42783/], count 0
[rosout][ERROR] 2020-02-27 09:00:56,570: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,602: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rospy.init][INFO] 2020-02-27 09:00:56,621: registered with master
[rospy.rosout][INFO] 2020-02-27 09:00:56,622: initializing /rosout core topic
[rospy.rosout][INFO] 2020-02-27 09:00:56,626: connected to core topic /rosout
[rospy.simtime][INFO] 2020-02-27 09:00:56,628: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2020-02-27 09:00:56,649: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,668: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,702: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,743: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,775: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,803: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,845: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,882: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rospy.internal][INFO] 2020-02-27 09:00:56,892: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2020-02-27 09:00:56,918: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,945: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:56,990: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,022: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,036: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,070: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,111: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,148: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,175: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,204: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,237: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,276: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,313: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,339: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,372: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,405: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,453: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,474: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,517: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,543: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,578: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,618: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,657: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,684: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,723: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,743: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,794: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,817: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,848: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,889: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,911: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,944: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:57,989: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:58,010: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rosout][ERROR] 2020-02-27 09:00:58,049: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rospy.core][INFO] 2020-02-27 09:00:58,088: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-02-27 09:00:58,095: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-02-27 09:00:58,096: topic[/usb_cam/image_rect] removing connection to http://itachi-HP-Pavilion-Laptop-15-cc1xx:42783/
[rospy.impl.masterslave][INFO] 2020-02-27 09:00:58,096: signal-2
[rospy.rosout][ERROR] 2020-02-27 09:00:58,097: Unable to report rosout: publish() to a closed topic
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/rosout.py", line 91, in _rosout
    _rosout_pub.publish(l)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 1041, in publish
    raise ROSException("publish() to a closed topic")
ROSException: publish() to a closed topic

[rosout][ERROR] 2020-02-27 09:00:58,095: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f63c65c4ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 25, in callback
    lower_red = np.array([124,61,40], dtype=np.uint8)
NameError: global name 'np' is not defined

[rospy.core][INFO] 2020-02-27 09:00:58,711: signal_shutdown [atexit]
