[rospy.client][INFO] 2020-01-31 16:38:04,766: init_node, name[/sr_determine_rois_10239_1580468884724], pid[10239]
[xmlrpc][INFO] 2020-01-31 16:38:04,767: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-01-31 16:38:04,767: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:35739/]
[rospy.init][INFO] 2020-01-31 16:38:04,767: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:35739/]
[rospy.impl.masterslave][INFO] 2020-01-31 16:38:04,767: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:35739/
[rospy.registration][INFO] 2020-01-31 16:38:04,768: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-01-31 16:38:04,768: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-01-31 16:38:04,768: registering subscriber topic [/usb_cam/image_rect] type [sensor_msgs/Image] with master
[rospy.internal][INFO] 2020-01-31 16:38:04,770: topic[/usb_cam/image_rect] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:45585/], count 0
[rosout][ERROR] 2020-01-31 16:38:04,823: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:04,865: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rospy.init][INFO] 2020-01-31 16:38:04,867: registered with master
[rospy.rosout][INFO] 2020-01-31 16:38:04,868: initializing /rosout core topic
[rospy.rosout][INFO] 2020-01-31 16:38:04,870: connected to core topic /rosout
[rospy.simtime][INFO] 2020-01-31 16:38:04,872: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2020-01-31 16:38:04,889: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:04,917: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:04,955: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:04,987: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,021: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,066: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rospy.internal][INFO] 2020-01-31 16:38:05,086: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2020-01-31 16:38:05,089: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,121: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,157: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,190: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,242: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,265: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,307: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,328: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,373: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,391: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,450: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,459: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,491: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,537: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,557: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,595: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,642: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,662: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,705: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,736: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,760: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,789: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,834: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,852: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,887: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,943: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,971: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:05,994: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,031: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,062: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,112: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,124: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,157: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,207: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,225: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,262: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,292: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,327: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,357: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,391: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,437: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,457: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,497: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,542: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,576: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,606: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,631: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,679: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,699: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,733: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,765: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,804: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,844: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,867: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,904: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,948: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:06,973: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:07,016: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:38:07,034: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f7d2c839a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rospy.core][INFO] 2020-01-31 16:38:07,039: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-01-31 16:38:07,043: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-01-31 16:38:07,043: topic[/usb_cam/image_rect] removing connection to http://itachi-HP-Pavilion-Laptop-15-cc1xx:45585/
[rospy.topics][ERROR] 2020-01-31 16:38:07,044: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2020-01-31 16:38:07,044: signal-2
[rospy.internal][WARNING] 2020-01-31 16:38:07,045: Unknown error initiating TCP/IP socket to itachi-HP-Pavilion-Laptop-15-cc1xx:38437 (http://itachi-HP-Pavilion-Laptop-15-cc1xx:45585/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-01-31 16:38:07,209: signal_shutdown [atexit]
