[rospy.client][INFO] 2020-01-31 16:33:58,266: init_node, name[/sr_determine_rois_9947_1580468638228], pid[9947]
[xmlrpc][INFO] 2020-01-31 16:33:58,267: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-01-31 16:33:58,267: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:46577/]
[rospy.init][INFO] 2020-01-31 16:33:58,267: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:46577/]
[rospy.impl.masterslave][INFO] 2020-01-31 16:33:58,268: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:46577/
[rospy.registration][INFO] 2020-01-31 16:33:58,269: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-01-31 16:33:58,269: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-01-31 16:33:58,269: registering subscriber topic [/usb_cam/image_rect] type [sensor_msgs/Image] with master
[rospy.internal][INFO] 2020-01-31 16:33:58,274: topic[/usb_cam/image_rect] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:45585/], count 0
[rosout][ERROR] 2020-01-31 16:33:58,331: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,358: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rospy.init][INFO] 2020-01-31 16:33:58,368: registered with master
[rospy.rosout][INFO] 2020-01-31 16:33:58,368: initializing /rosout core topic
[rospy.rosout][INFO] 2020-01-31 16:33:58,371: connected to core topic /rosout
[rospy.simtime][INFO] 2020-01-31 16:33:58,373: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2020-01-31 16:33:58,391: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,435: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,453: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,485: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rospy.internal][INFO] 2020-01-31 16:33:58,489: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2020-01-31 16:33:58,513: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,548: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,595: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,618: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,652: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,683: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,719: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,763: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,801: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,836: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,860: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,891: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,936: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,954: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:58,994: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,022: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,051: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,099: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,117: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,154: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,192: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,221: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,259: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,292: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,334: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,360: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,390: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,430: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,464: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,500: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,527: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,555: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,589: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,628: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,661: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,701: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,728: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,756: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,804: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,838: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,877: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,897: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,928: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:33:59,960: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,003: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,022: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,072: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,112: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,127: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,177: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,199: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,240: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,288: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,315: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,343: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,378: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,397: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,445: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,462: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,500: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,534: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,572: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,613: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,631: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,664: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,699: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,744: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,772: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,814: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,849: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,878: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,894: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,931: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:00,973: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,009: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,036: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,075: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,102: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,151: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,187: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,204: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,244: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,288: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,311: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,336: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,381: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,405: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,451: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,482: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,517: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,552: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,585: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,602: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,635: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,681: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,704: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,737: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,773: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,804: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,852: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,874: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,917: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,943: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:01,974: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,007: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,047: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,074: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,109: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,156: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,176: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,205: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,242: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,287: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,329: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,349: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,381: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rosout][ERROR] 2020-01-31 16:34:02,425: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7fecaa728a70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 43, in image_callback
    cv2.imshow("Detected ROIs", img_copy)
UnboundLocalError: local variable 'img_copy' referenced before assignment

[rospy.core][INFO] 2020-01-31 16:34:02,448: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-01-31 16:34:02,454: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-01-31 16:34:02,454: topic[/usb_cam/image_rect] removing connection to http://itachi-HP-Pavilion-Laptop-15-cc1xx:45585/
[rospy.topics][ERROR] 2020-01-31 16:34:02,455: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2020-01-31 16:34:02,455: signal-2
[rospy.internal][WARNING] 2020-01-31 16:34:02,455: Unknown error initiating TCP/IP socket to itachi-HP-Pavilion-Laptop-15-cc1xx:38437 (http://itachi-HP-Pavilion-Laptop-15-cc1xx:45585/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-01-31 16:34:02,619: signal_shutdown [atexit]
