[rospy.client][INFO] 2020-01-30 23:13:19,528: init_node, name[/sr_determine_rois_6204_1580406199488], pid[6204]
[xmlrpc][INFO] 2020-01-30 23:13:19,529: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-01-30 23:13:19,529: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:35443/]
[rospy.init][INFO] 2020-01-30 23:13:19,530: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:35443/]
[rospy.impl.masterslave][INFO] 2020-01-30 23:13:19,530: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:35443/
[xmlrpc][INFO] 2020-01-30 23:13:19,530: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-01-30 23:13:19,530: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2020-01-30 23:13:19,531: registering subscriber topic [/usb_cam/image_rect] type [sensor_msgs/Image] with master
[rospy.internal][INFO] 2020-01-30 23:13:19,540: topic[/usb_cam/image_rect] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:38025/], count 0
[rosout][ERROR] 2020-01-30 23:13:19,583: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,612: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rospy.init][INFO] 2020-01-30 23:13:19,630: registered with master
[rospy.rosout][INFO] 2020-01-30 23:13:19,630: initializing /rosout core topic
[rospy.rosout][INFO] 2020-01-30 23:13:19,633: connected to core topic /rosout
[rospy.simtime][INFO] 2020-01-30 23:13:19,635: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2020-01-30 23:13:19,640: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,677: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,715: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,736: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,783: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,801: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,845: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rospy.internal][INFO] 2020-01-30 23:13:19,863: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2020-01-30 23:13:19,874: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,905: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,942: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:19,972: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,002: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,040: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,083: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,108: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,152: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,173: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,201: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,242: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,270: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,312: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,348: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,374: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,414: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,443: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,477: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,520: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,538: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,576: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,609: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,638: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,688: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,705: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,742: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,779: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,806: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,842: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,879: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,907: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,952: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:20,980: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,009: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,043: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,089: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,112: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,149: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,177: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,211: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,251: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,283: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,325: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,347: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,381: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,415: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,446: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,480: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,524: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,552: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,582: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,616: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,663: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,693: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,720: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,763: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,781: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,831: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,848: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,882: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,925: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,953: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:21,987: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,017: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,050: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,085: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,132: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,149: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,193: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,220: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,268: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,286: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,315: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,358: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,383: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,422: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,460: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,506: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,520: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,556: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,594: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,636: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,665: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,692: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,726: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,766: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,791: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,828: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,863: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,887: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,921: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:22,960: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,001: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,020: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,058: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,090: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,135: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,159: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,200: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,229: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,257: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,288: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,328: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,373: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,404: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,439: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,455: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,504: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,526: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,570: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,594: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,627: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,665: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,698: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,733: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,763: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,801: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,827: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,859: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,893: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,928: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,978: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:23,996: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,042: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,077: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,093: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,137: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,177: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,198: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,230: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,274: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,305: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,335: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,364: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,397: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,435: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,482: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,503: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,532: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,577: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,613: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,644: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,665: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,701: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,732: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,767: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,810: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,843: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,869: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,905: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,935: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:24,968: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,014: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,033: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,070: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,113: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,138: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,167: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,217: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,253: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,284: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,317: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,336: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,381: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,416: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,446: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,482: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,504: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,538: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,567: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,617: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,651: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,679: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,707: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,751: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,772: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,804: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,842: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,877: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,908: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,942: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:25,980: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,009: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,040: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,079: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,105: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,154: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,186: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,215: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,245: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,281: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,312: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,350: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,375: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,423: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,457: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,484: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,512: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,548: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,587: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,619: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,653: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,677: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,711: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,746: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,777: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,808: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,854: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,885: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,928: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,949: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:26,992: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,012: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,064: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,082: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,112: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,154: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,193: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,223: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,258: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,290: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,316: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,350: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,394: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,419: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,450: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,492: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,527: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,555: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,603: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,630: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,656: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,701: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,721: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,759: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,794: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,820: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,871: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,890: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,932: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,967: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:27,994: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:28,019: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:28,055: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:28,100: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:28,119: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:28,155: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2020-01-30 23:13:28,188: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f8fdb0c8b48>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc.py", line 25, in callback
    (rows,cols,channels) = self.cv_image.shape
ValueError: need more than 2 values to unpack

[rospy.core][INFO] 2020-01-30 23:13:28,210: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-01-30 23:13:28,213: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-01-30 23:13:28,214: topic[/usb_cam/image_rect] removing connection to http://itachi-HP-Pavilion-Laptop-15-cc1xx:38025/
[rospy.impl.masterslave][INFO] 2020-01-30 23:13:28,214: signal-2
[rospy.core][INFO] 2020-01-30 23:13:28,378: signal_shutdown [atexit]
